# Investor - Flow of Funds - US

### Introduction:

Special thanks to: https://github.com/rgrp for sharing the dataset.

### Step 1. Import the necessary libraries

In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

%matplotlib inline

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv).

### Step 3. Assign it to a variable called

In [12]:
url = 'https://raw.githubusercontent.com/datasets/investor-flow-of-funds-us/master/data/weekly.csv'
df = pd.read_csv(url)
df.head()

,Date,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
0,2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
1,2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2,2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
3,2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
4,2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 4.  What is the frequency of the dataset?

In [13]:
#it is weekly data

### Step 5. Set the column Date as the index.

In [14]:
df.set_index('Date', inplace=True)
df.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-06,10167,NaN,3058,NaN,842,NaN,2216,NaN
2022-07-13,7409,NaN,2808,NaN,2067,NaN,741,NaN
2022-07-20,3468,NaN,102,NaN,-417,NaN,519,NaN
2022-07-27,14213,NaN,9667,NaN,8598,NaN,1069,NaN
2022-08-03,9786,NaN,4016,NaN,3079,NaN,937,NaN

### Step 6. What is the type of the index?

In [15]:
type(df.index)

pandas.core.indexes.base.Index

### Step 7. Set the index to a DatetimeIndex type

In [16]:
df.index = pd.to_datetime(df.index)
type(df.index)

pandas.core.indexes.datetimes.DatetimeIndex

### Step 8.  Change the frequency to monthly, sum the values and assign it to monthly.

In [17]:
monthly = df.resample('ME').sum(min_count=1)
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257.0,NaN,15635.0,NaN,11090.0,NaN,4545.0,NaN
2022-08-31,48596.0,NaN,32348.0,NaN,33705.0,NaN,-1357.0,NaN
2022-09-30,13775.0,NaN,10324.0,NaN,11629.0,NaN,-1305.0,NaN
2022-10-31,82879.0,NaN,55644.0,NaN,47435.0,NaN,8209.0,NaN
2022-11-30,82731.0,NaN,54314.0,NaN,37348.0,NaN,16967.0,NaN

### Step 9. You will notice that it filled the dataFrame with months that don't have any data with NaN. Let's drop these rows.

In [19]:
monthly.dropna(how='all')

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-07-31,35257.0,NaN,15635.0,NaN,11090.0,NaN,4545.0,NaN
2022-08-31,48596.0,NaN,32348.0,NaN,33705.0,NaN,-1357.0,NaN
2022-09-30,13775.0,NaN,10324.0,NaN,11629.0,NaN,-1305.0,NaN
2022-10-31,82879.0,NaN,55644.0,NaN,47435.0,NaN,8209.0,NaN
2022-11-30,82731.0,NaN,54314.0,NaN,37348.0,NaN,16967.0,NaN
2022-12-31,40451.0,NaN,29124.0,NaN,18273.0,NaN,10849.0,NaN
2023-01-31,34891.0,NaN,7849.0,NaN,-9996.0,NaN,17845.0,NaN
2023-02-28,13284.0,NaN,16508.0,NaN,6243.0,NaN,10264.0,NaN
2023-03-31,28856.0,NaN,3713.0,NaN,2500.0,NaN,1213.0,NaN
2023-04-30,39723.0,NaN,19058.0,NaN,14426.0,NaN,4632.0,NaN
2023-05-31,23789.0,NaN,6377.0,NaN,2020.0,NaN,4358.0,NaN
2023-06-30,62472.0,NaN,50672.0,NaN,39254.0,NaN,11416.0,NaN
2023-07-31,63164.0,NaN,46019.0,NaN,38479.0,NaN,7539.0,NaN
2023-08-31,18731.0,NaN,11968.0,NaN,10880.0,NaN,1089.0,NaN
2023-09-30,37875.0,NaN,29963.0,NaN,29830.0,NaN,133.0,NaN
2023-10-31,27572.0,NaN,13947.0,NaN,14375.0,NaN,-429.0,NaN
2023-11-30,114386.0,NaN,78843.0,NaN,73411.0,NaN,5433.0,NaN
2023-12-31,112558.0,NaN,99097.0,NaN,80368.0,NaN,18729.0,NaN
2024-01-31,58899.0,NaN,36802.0,NaN,30780.0,NaN,6022.0,NaN
2024-02-29,44097.0,NaN,35905.0,NaN,27097.0,NaN,8809.0,NaN
2024-03-31,105578.0,NaN,87666.0,NaN,76618.0,NaN,11047.0,NaN
2024-05-31,79344.0,NaN,51938.0,NaN,42353.0,NaN,9584.0,NaN
2024-06-30,79138.0,NaN,51872.0,NaN,39741.0,NaN,12131.0,NaN
2024-07-31,134078.0,NaN,98285.0,NaN,95686.0,NaN,2598.0,NaN
2025-09-30,125005.0,NaN,72886.0,NaN,48603.0,NaN,24282.0,NaN
2025-10-31,79460.0,NaN,53892.0,NaN,42312.0,NaN,11580.0,NaN
2026-01-31,40488.0,NaN,24250.0,NaN,4252.0,NaN,19997.0,NaN
2026-02-28,183583.0,NaN,108357.0,NaN,49584.0,NaN,58773.0,NaN

### Step 10. Good, now we have the monthly data. Now change the frequency to year.

In [21]:
monthly = df.resample('YS').sum()
monthly.head()

,Total Equity,Domestic Equity,World Equity,Hybrid,Total Bond,Taxable Bond,Municipal Bond,Total
Date,,,,,,,,
2022-01-01,303689,0.0,197389,0.0,159480,0.0,37908,0.0
2023-01-01,577301,0.0,384014,0.0,301790,0.0,82222,0.0
2024-01-01,501134,0.0,362468,0.0,312275,0.0,50191,0.0
2025-01-01,204465,0.0,126778,0.0,90915,0.0,35862,0.0
2026-01-01,224071,0.0,132607,0.0,53836,0.0,78770,0.0

### BONUS: Create your own question and answer it.